(cl:defpackage my_robot_msgs-msg
  (:use )
  (:export
   "<MOVEUNTILACTION>"
   "MOVEUNTILACTION"
   "<MOVEUNTILACTIONFEEDBACK>"
   "MOVEUNTILACTIONFEEDBACK"
   "<MOVEUNTILACTIONGOAL>"
   "MOVEUNTILACTIONGOAL"
   "<MOVEUNTILACTIONRESULT>"
   "MOVEUNTILACTIONRESULT"
   "<MOVEUNTILFEEDBACK>"
   "MOVEUNTILFEEDBACK"
   "<MOVEUNTILGOAL>"
   "MOVEUNTILGOAL"
   "<MOVEUNTILRESULT>"
   "MOVEUNTILRESULT"
  ))

