; Auto-generated. Do not edit!


(cl:in-package my_robot_msgs-msg)


;//! \htmlinclude MoveUntilResult.msg.html

(cl:defclass <MoveUntilResult> (roslisp-msg-protocol:ros-message)
  ((Error
    :reader Error
    :initarg :Error
    :type cl:float
    :initform 0.0))
)

(cl:defclass MoveUntilResult (<MoveUntilResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveUntilResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveUntilResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_robot_msgs-msg:<MoveUntilResult> is deprecated: use my_robot_msgs-msg:MoveUntilResult instead.")))

(cl:ensure-generic-function 'Error-val :lambda-list '(m))
(cl:defmethod Error-val ((m <MoveUntilResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_robot_msgs-msg:Error-val is deprecated.  Use my_robot_msgs-msg:Error instead.")
  (Error m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveUntilResult>) ostream)
  "Serializes a message object of type '<MoveUntilResult>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'Error))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveUntilResult>) istream)
  "Deserializes a message object of type '<MoveUntilResult>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'Error) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveUntilResult>)))
  "Returns string type for a message object of type '<MoveUntilResult>"
  "my_robot_msgs/MoveUntilResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveUntilResult)))
  "Returns string type for a message object of type 'MoveUntilResult"
  "my_robot_msgs/MoveUntilResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveUntilResult>)))
  "Returns md5sum for a message object of type '<MoveUntilResult>"
  "bf06f29f21152ea7e6b7d58ff2a92f4d")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveUntilResult)))
  "Returns md5sum for a message object of type 'MoveUntilResult"
  "bf06f29f21152ea7e6b7d58ff2a92f4d")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveUntilResult>)))
  "Returns full string definition for message of type '<MoveUntilResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%float64 Error~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveUntilResult)))
  "Returns full string definition for message of type 'MoveUntilResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%float64 Error~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveUntilResult>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveUntilResult>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveUntilResult
    (cl:cons ':Error (Error msg))
))
