; Auto-generated. Do not edit!


(cl:in-package my_robot_msgs-msg)


;//! \htmlinclude MoveUntilFeedback.msg.html

(cl:defclass <MoveUntilFeedback> (roslisp-msg-protocol:ros-message)
  ((Percentage
    :reader Percentage
    :initarg :Percentage
    :type cl:float
    :initform 0.0))
)

(cl:defclass MoveUntilFeedback (<MoveUntilFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveUntilFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveUntilFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_robot_msgs-msg:<MoveUntilFeedback> is deprecated: use my_robot_msgs-msg:MoveUntilFeedback instead.")))

(cl:ensure-generic-function 'Percentage-val :lambda-list '(m))
(cl:defmethod Percentage-val ((m <MoveUntilFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_robot_msgs-msg:Percentage-val is deprecated.  Use my_robot_msgs-msg:Percentage instead.")
  (Percentage m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveUntilFeedback>) ostream)
  "Serializes a message object of type '<MoveUntilFeedback>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'Percentage))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveUntilFeedback>) istream)
  "Deserializes a message object of type '<MoveUntilFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'Percentage) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveUntilFeedback>)))
  "Returns string type for a message object of type '<MoveUntilFeedback>"
  "my_robot_msgs/MoveUntilFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveUntilFeedback)))
  "Returns string type for a message object of type 'MoveUntilFeedback"
  "my_robot_msgs/MoveUntilFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveUntilFeedback>)))
  "Returns md5sum for a message object of type '<MoveUntilFeedback>"
  "b87f441dd44984efdefcf09d1ae73031")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveUntilFeedback)))
  "Returns md5sum for a message object of type 'MoveUntilFeedback"
  "b87f441dd44984efdefcf09d1ae73031")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveUntilFeedback>)))
  "Returns full string definition for message of type '<MoveUntilFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%float64 Percentage~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveUntilFeedback)))
  "Returns full string definition for message of type 'MoveUntilFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%float64 Percentage~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveUntilFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveUntilFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveUntilFeedback
    (cl:cons ':Percentage (Percentage msg))
))
