; Auto-generated. Do not edit!


(cl:in-package my_robot_msgs-msg)


;//! \htmlinclude MoveUntilGoal.msg.html

(cl:defclass <MoveUntilGoal> (roslisp-msg-protocol:ros-message)
  ((Min_error
    :reader Min_error
    :initarg :Min_error
    :type cl:float
    :initform 0.0))
)

(cl:defclass MoveUntilGoal (<MoveUntilGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveUntilGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveUntilGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_robot_msgs-msg:<MoveUntilGoal> is deprecated: use my_robot_msgs-msg:MoveUntilGoal instead.")))

(cl:ensure-generic-function 'Min_error-val :lambda-list '(m))
(cl:defmethod Min_error-val ((m <MoveUntilGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_robot_msgs-msg:Min_error-val is deprecated.  Use my_robot_msgs-msg:Min_error instead.")
  (Min_error m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveUntilGoal>) ostream)
  "Serializes a message object of type '<MoveUntilGoal>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'Min_error))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveUntilGoal>) istream)
  "Deserializes a message object of type '<MoveUntilGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'Min_error) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveUntilGoal>)))
  "Returns string type for a message object of type '<MoveUntilGoal>"
  "my_robot_msgs/MoveUntilGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveUntilGoal)))
  "Returns string type for a message object of type 'MoveUntilGoal"
  "my_robot_msgs/MoveUntilGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveUntilGoal>)))
  "Returns md5sum for a message object of type '<MoveUntilGoal>"
  "329a6d4b69a6e44522f1d579d9ca32e2")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveUntilGoal)))
  "Returns md5sum for a message object of type 'MoveUntilGoal"
  "329a6d4b69a6e44522f1d579d9ca32e2")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveUntilGoal>)))
  "Returns full string definition for message of type '<MoveUntilGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal ~%float64 Min_error~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveUntilGoal)))
  "Returns full string definition for message of type 'MoveUntilGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal ~%float64 Min_error~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveUntilGoal>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveUntilGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveUntilGoal
    (cl:cons ':Min_error (Min_error msg))
))
