// Generated by gencpp from file my_robot_msgs/MoveUntilGoal.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MSGS_MESSAGE_MOVEUNTILGOAL_H
#define MY_ROBOT_MSGS_MESSAGE_MOVEUNTILGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_robot_msgs
{
template <class ContainerAllocator>
struct MoveUntilGoal_
{
  typedef MoveUntilGoal_<ContainerAllocator> Type;

  MoveUntilGoal_()
    : Min_error(0.0)  {
    }
  MoveUntilGoal_(const ContainerAllocator& _alloc)
    : Min_error(0.0)  {
  (void)_alloc;
    }



   typedef double _Min_error_type;
  _Min_error_type Min_error;





  typedef boost::shared_ptr< ::my_robot_msgs::MoveUntilGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot_msgs::MoveUntilGoal_<ContainerAllocator> const> ConstPtr;

}; // struct MoveUntilGoal_

typedef ::my_robot_msgs::MoveUntilGoal_<std::allocator<void> > MoveUntilGoal;

typedef boost::shared_ptr< ::my_robot_msgs::MoveUntilGoal > MoveUntilGoalPtr;
typedef boost::shared_ptr< ::my_robot_msgs::MoveUntilGoal const> MoveUntilGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot_msgs::MoveUntilGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot_msgs::MoveUntilGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_robot_msgs::MoveUntilGoal_<ContainerAllocator1> & lhs, const ::my_robot_msgs::MoveUntilGoal_<ContainerAllocator2> & rhs)
{
  return lhs.Min_error == rhs.Min_error;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_robot_msgs::MoveUntilGoal_<ContainerAllocator1> & lhs, const ::my_robot_msgs::MoveUntilGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::MoveUntilGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::MoveUntilGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::MoveUntilGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::MoveUntilGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::MoveUntilGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::MoveUntilGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot_msgs::MoveUntilGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "329a6d4b69a6e44522f1d579d9ca32e2";
  }

  static const char* value(const ::my_robot_msgs::MoveUntilGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x329a6d4b69a6e445ULL;
  static const uint64_t static_value2 = 0x22f1d579d9ca32e2ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot_msgs::MoveUntilGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot_msgs/MoveUntilGoal";
  }

  static const char* value(const ::my_robot_msgs::MoveUntilGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot_msgs::MoveUntilGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal \n"
"float64 Min_error\n"
;
  }

  static const char* value(const ::my_robot_msgs::MoveUntilGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot_msgs::MoveUntilGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Min_error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveUntilGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot_msgs::MoveUntilGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot_msgs::MoveUntilGoal_<ContainerAllocator>& v)
  {
    s << indent << "Min_error: ";
    Printer<double>::stream(s, indent + "  ", v.Min_error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_MSGS_MESSAGE_MOVEUNTILGOAL_H
