// Generated by gencpp from file my_robot_msgs/MoveUntilResult.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MSGS_MESSAGE_MOVEUNTILRESULT_H
#define MY_ROBOT_MSGS_MESSAGE_MOVEUNTILRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_robot_msgs
{
template <class ContainerAllocator>
struct MoveUntilResult_
{
  typedef MoveUntilResult_<ContainerAllocator> Type;

  MoveUntilResult_()
    : Error(0.0)  {
    }
  MoveUntilResult_(const ContainerAllocator& _alloc)
    : Error(0.0)  {
  (void)_alloc;
    }



   typedef double _Error_type;
  _Error_type Error;





  typedef boost::shared_ptr< ::my_robot_msgs::MoveUntilResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot_msgs::MoveUntilResult_<ContainerAllocator> const> ConstPtr;

}; // struct MoveUntilResult_

typedef ::my_robot_msgs::MoveUntilResult_<std::allocator<void> > MoveUntilResult;

typedef boost::shared_ptr< ::my_robot_msgs::MoveUntilResult > MoveUntilResultPtr;
typedef boost::shared_ptr< ::my_robot_msgs::MoveUntilResult const> MoveUntilResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot_msgs::MoveUntilResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot_msgs::MoveUntilResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_robot_msgs::MoveUntilResult_<ContainerAllocator1> & lhs, const ::my_robot_msgs::MoveUntilResult_<ContainerAllocator2> & rhs)
{
  return lhs.Error == rhs.Error;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_robot_msgs::MoveUntilResult_<ContainerAllocator1> & lhs, const ::my_robot_msgs::MoveUntilResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::MoveUntilResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::MoveUntilResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::MoveUntilResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::MoveUntilResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::MoveUntilResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::MoveUntilResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot_msgs::MoveUntilResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bf06f29f21152ea7e6b7d58ff2a92f4d";
  }

  static const char* value(const ::my_robot_msgs::MoveUntilResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbf06f29f21152ea7ULL;
  static const uint64_t static_value2 = 0xe6b7d58ff2a92f4dULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot_msgs::MoveUntilResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot_msgs/MoveUntilResult";
  }

  static const char* value(const ::my_robot_msgs::MoveUntilResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot_msgs::MoveUntilResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result\n"
"float64 Error\n"
;
  }

  static const char* value(const ::my_robot_msgs::MoveUntilResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot_msgs::MoveUntilResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveUntilResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot_msgs::MoveUntilResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot_msgs::MoveUntilResult_<ContainerAllocator>& v)
  {
    s << indent << "Error: ";
    Printer<double>::stream(s, indent + "  ", v.Error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_MSGS_MESSAGE_MOVEUNTILRESULT_H
