// Generated by gencpp from file my_robot_msgs/MoveUntilFeedback.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MSGS_MESSAGE_MOVEUNTILFEEDBACK_H
#define MY_ROBOT_MSGS_MESSAGE_MOVEUNTILFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_robot_msgs
{
template <class ContainerAllocator>
struct MoveUntilFeedback_
{
  typedef MoveUntilFeedback_<ContainerAllocator> Type;

  MoveUntilFeedback_()
    : Percentage(0.0)  {
    }
  MoveUntilFeedback_(const ContainerAllocator& _alloc)
    : Percentage(0.0)  {
  (void)_alloc;
    }



   typedef double _Percentage_type;
  _Percentage_type Percentage;





  typedef boost::shared_ptr< ::my_robot_msgs::MoveUntilFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot_msgs::MoveUntilFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct MoveUntilFeedback_

typedef ::my_robot_msgs::MoveUntilFeedback_<std::allocator<void> > MoveUntilFeedback;

typedef boost::shared_ptr< ::my_robot_msgs::MoveUntilFeedback > MoveUntilFeedbackPtr;
typedef boost::shared_ptr< ::my_robot_msgs::MoveUntilFeedback const> MoveUntilFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot_msgs::MoveUntilFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot_msgs::MoveUntilFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_robot_msgs::MoveUntilFeedback_<ContainerAllocator1> & lhs, const ::my_robot_msgs::MoveUntilFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.Percentage == rhs.Percentage;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_robot_msgs::MoveUntilFeedback_<ContainerAllocator1> & lhs, const ::my_robot_msgs::MoveUntilFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::MoveUntilFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::MoveUntilFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::MoveUntilFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::MoveUntilFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::MoveUntilFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::MoveUntilFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot_msgs::MoveUntilFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b87f441dd44984efdefcf09d1ae73031";
  }

  static const char* value(const ::my_robot_msgs::MoveUntilFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb87f441dd44984efULL;
  static const uint64_t static_value2 = 0xdefcf09d1ae73031ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot_msgs::MoveUntilFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot_msgs/MoveUntilFeedback";
  }

  static const char* value(const ::my_robot_msgs::MoveUntilFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot_msgs::MoveUntilFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"\n"
"float64 Percentage\n"
"\n"
;
  }

  static const char* value(const ::my_robot_msgs::MoveUntilFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot_msgs::MoveUntilFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Percentage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveUntilFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot_msgs::MoveUntilFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot_msgs::MoveUntilFeedback_<ContainerAllocator>& v)
  {
    s << indent << "Percentage: ";
    Printer<double>::stream(s, indent + "  ", v.Percentage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_MSGS_MESSAGE_MOVEUNTILFEEDBACK_H
