filepath:
  coppeliasim: ~/CoppeliaSim_Edu_V4_6_0_rev14_Ubuntu20_04/coppeliaSim
  scene: ../testspace/test_first_setup.ttt
  urdf: ../urdf/iiwa7.urdf
robot:
  ee_name: iiwa_link_ee
  base_name: iiwa_link_0
  init_pos: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  init_cmd: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  control_type: Force # Position, Velocity, Force
