filepath:
  coppeliasim: ~/CoppeliaSim_Edu_V4_6_0_rev14_Ubuntu20_04/coppeliaSim
  scene: ../plenary_meeting/empty_surface_finishing.ttt
  urdf: ../urdf/cobod_arm_6DOF.urdf
robot:
  ee_name: iiwa_link_ee
  base_name: iiwa_link_0
  xyz: [2.0, 2.0, 0.0]
  rpy: [0.0, 0.0, 0.0]
  init_pos: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  init_cmd: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  control_type: Force # Position, Velocity, Force
