// Generated by gencpp from file send_pos/AddTwoInts.msg
// DO NOT EDIT!


#ifndef SEND_POS_MESSAGE_ADDTWOINTS_H
#define SEND_POS_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <send_pos/AddTwoIntsRequest.h>
#include <send_pos/AddTwoIntsResponse.h>


namespace send_pos
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace send_pos


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::send_pos::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::send_pos::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::send_pos::AddTwoInts > {
  static const char* value()
  {
    return "send_pos/AddTwoInts";
  }

  static const char* value(const ::send_pos::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::send_pos::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::send_pos::AddTwoInts >
template<>
struct MD5Sum< ::send_pos::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::send_pos::AddTwoInts >::value();
  }
  static const char* value(const ::send_pos::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::send_pos::AddTwoIntsRequest> should match
// service_traits::DataType< ::send_pos::AddTwoInts >
template<>
struct DataType< ::send_pos::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::send_pos::AddTwoInts >::value();
  }
  static const char* value(const ::send_pos::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::send_pos::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::send_pos::AddTwoInts >
template<>
struct MD5Sum< ::send_pos::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::send_pos::AddTwoInts >::value();
  }
  static const char* value(const ::send_pos::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::send_pos::AddTwoIntsResponse> should match
// service_traits::DataType< ::send_pos::AddTwoInts >
template<>
struct DataType< ::send_pos::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::send_pos::AddTwoInts >::value();
  }
  static const char* value(const ::send_pos::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SEND_POS_MESSAGE_ADDTWOINTS_H
