// Auto-generated. Do not edit!

// (in-package my_robot_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class MoveUntilResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.Error = null;
    }
    else {
      if (initObj.hasOwnProperty('Error')) {
        this.Error = initObj.Error
      }
      else {
        this.Error = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type MoveUntilResult
    // Serialize message field [Error]
    bufferOffset = _serializer.float64(obj.Error, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type MoveUntilResult
    let len;
    let data = new MoveUntilResult(null);
    // Deserialize message field [Error]
    data.Error = _deserializer.float64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'my_robot_msgs/MoveUntilResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'bf06f29f21152ea7e6b7d58ff2a92f4d';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result
    float64 Error
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new MoveUntilResult(null);
    if (msg.Error !== undefined) {
      resolved.Error = msg.Error;
    }
    else {
      resolved.Error = 0.0
    }

    return resolved;
    }
};

module.exports = MoveUntilResult;
