// Auto-generated. Do not edit!

// (in-package my_robot_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class MoveUntilFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.Percentage = null;
    }
    else {
      if (initObj.hasOwnProperty('Percentage')) {
        this.Percentage = initObj.Percentage
      }
      else {
        this.Percentage = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type MoveUntilFeedback
    // Serialize message field [Percentage]
    bufferOffset = _serializer.float64(obj.Percentage, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type MoveUntilFeedback
    let len;
    let data = new MoveUntilFeedback(null);
    // Deserialize message field [Percentage]
    data.Percentage = _deserializer.float64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'my_robot_msgs/MoveUntilFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'b87f441dd44984efdefcf09d1ae73031';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #feedback
    
    float64 Percentage
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new MoveUntilFeedback(null);
    if (msg.Percentage !== undefined) {
      resolved.Percentage = msg.Percentage;
    }
    else {
      resolved.Percentage = 0.0
    }

    return resolved;
    }
};

module.exports = MoveUntilFeedback;
